"""Add user model

Revision ID: 154e0e7f20e1
Revises: bad2247337d8
Create Date: 2025-10-16 19:42:42.929772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '154e0e7f20e1'
down_revision = 'bad2247337d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_reservation_user_id', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.drop_constraint('fk_reservation_user_id', type_='foreignkey')

    # ### end Alembic commands ###
