"""Add description to MeetingRoom

Revision ID: 898589d427e1
Revises: 7a8498a23292
Create Date: 2025-10-12 13:22:59.680117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '898589d427e1'
down_revision = '7a8498a23292'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetingroom', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetingroom', 'description')
    # ### end Alembic commands ###
